"""Rotas da API do domínio de professores."""

from django.urls import path

from apps.professores.api.views import (
    AtribuicaoDisciplinaDataTickView,
    AtribuicaoDisciplinaDataView,
    AtribuicaoPeriodoView,
    AtribuicaoRecorrenciaDatasView,
    AtribuicaoStatusView,
    AtribuicaoTurmasListaView,
    AtribuicaoVerificarDataView,
    AutoCompleteView,
    BuscaProfessoresAnoLetivoView,
    BuscaProfessoresView,
    BuscarPorListaRFView,
    BuscarPorRfAnoLetivoView,
    BuscarPorRfDreUeView,
    BuscarTurmasAtribuidasView,
    BuscaTurmasAtribuidasEscolaView,
    BuscaTurmasAtribuidasProfessorEscolaView,
    EhEmeiView,
    ObterNomePeloRFView,
    ObterProfessoresAtribuidosTurmaDiscView,
    TitularesPorTurmaAgrupamentoView,
    TitularesPorTurmasView,
    TitularesPorUeView,
    TitularPorTurmaDisciplinaView,
    VerificarValidadeView,
)

_BASE_PROF = "professores"
_BASE_ESC = "escolas"

urlpatterns = [
    path(
        f"{_BASE_PROF}/{_BASE_ESC}/<str:codigo_eol_escola>/{_BASE_PROF}/",
        BuscaProfessoresView.as_view(),
        name="professores-escola",
    ),
    path(
        f"{_BASE_PROF}/{_BASE_ESC}/<str:codigo_eol_escola>/"
        f"{_BASE_PROF}/<int:ano_letivo>/",
        BuscaProfessoresAnoLetivoView.as_view(),
        name="professores-escola-ano",
    ),
    path(
        f"{_BASE_PROF}/escolas/<str:codigo_eol_escola>"
        "/turmas/anos_letivos/<int:ano_letivo>/",
        BuscaTurmasAtribuidasEscolaView.as_view(),
        name="turmas-atribuidas-escola",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/escolas/<str:codigo_eol_escola>"
        "/turmas/anos_letivos/<int:ano_letivo>/",
        BuscaTurmasAtribuidasProfessorEscolaView.as_view(),
        name="turmas-atribuidas-rf-escola-ano",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/turmas/",
        BuscarTurmasAtribuidasView.as_view(),
        name="turmas-atribuidas-todas",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/turmas/anos_letivos/<int:ano_letivo>/",
        BuscarTurmasAtribuidasView.as_view(),
        name="turmas-atribuidas-ano",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/BuscarPorRf/<int:ano_letivo>/",
        BuscarPorRfAnoLetivoView.as_view(),
        name="professor-buscar-por-rf-ano",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/BuscarPorRfDreUe/<int:ano_letivo>/",
        BuscarPorRfDreUeView.as_view(),
        name="professor-buscar-por-rf-dre-ue",
    ),
    path(
        f"{_BASE_PROF}/<int:ano_letivo>/AutoComplete/<str:dre_id>/",
        AutoCompleteView.as_view(),
        name="professor-autocomplete",
    ),
    path(
        f"{_BASE_PROF}/<int:ano_letivo>/BuscarPorListaRF/",
        BuscarPorListaRFView.as_view(),
        name="professor-buscar-lista-rf",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/validade/",
        VerificarValidadeView.as_view(),
        name="professor-validade",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/ehEmei/",
        EhEmeiView.as_view(),
        name="professor-eh-emei",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/turmas/<int:codigo_turma>"
        "/atribuicao/status/",
        AtribuicaoStatusView.as_view(),
        name="professor-atribuicao-status",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/turmas/<int:codigo_turma>"
        "/atribuicao/verificar/data/",
        AtribuicaoVerificarDataView.as_view(),
        name="professor-atribuicao-verificar-data",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/turmas/<int:codigo_turma>"
        "/disciplinas/<int:disciplina_id>/atribuicao/verificar/data/",
        AtribuicaoDisciplinaDataView.as_view(),
        name="professor-atribuicao-disciplina-data",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/turmas/<int:codigo_turma>"
        "/disciplinas/<int:disciplina_id>/atribuicao/verificar/datatick/",
        AtribuicaoDisciplinaDataTickView.as_view(),
        name="professor-atribuicao-disciplina-datatick",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/turmas/<int:codigo_turma>"
        "/disciplinas/<int:disciplina_id>"
        "/atribuicao/recorrencia/verificar/datas/",
        AtribuicaoRecorrenciaDatasView.as_view(),
        name="professor-atribuicao-recorrencia-datas",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/disciplina/<int:disciplina_id>/turmas/",
        AtribuicaoTurmasListaView.as_view(),
        name="professor-atribuicao-turmas-lista",
    ),
    path(
        f"{_BASE_PROF}/<str:codigo_rf>/turmas/<int:codigo_turma>"
        "/componentes/<int:componente_curricular_id>"
        "/atribuicao/periodo/inicio/<str:data_inicio_periodo>"
        "/fim/<str:data_fim_periodo>/",
        AtribuicaoPeriodoView.as_view(),
        name="professor-atribuicao-periodo",
    ),
    path(
        f"{_BASE_PROF}/<int:codigo_turma>"
        "/disciplinas/<int:disciplina_id>/atribuicao/data/",
        ObterProfessoresAtribuidosTurmaDiscView.as_view(),
        name="professores-atribuidos-turma-disc",
    ),
    path(
        f"{_BASE_PROF}/titular/turmas/<int:codigo_turma>"
        "/componentes-curriculares/<int:codigo_componente_curricular>/",
        TitularPorTurmaDisciplinaView.as_view(),
        name="professor-titular-turma-disciplina",
    ),
    path(
        f"{_BASE_PROF}/titulares/",
        TitularesPorTurmasView.as_view(),
        name="professores-titulares",
    ),
    path(
        f"{_BASE_PROF}/<int:codigo_turma>"
        "/titulares/realizaAgrupamentoComponente/<str:realiza_agrupamento>/",
        TitularesPorTurmaAgrupamentoView.as_view(),
        name="professores-titulares-turma",
    ),
    path(
        f"{_BASE_PROF}/titulares/ue/<str:ue_codigo>/<str:data_referencia>/",
        TitularesPorUeView.as_view(),
        name="professores-titulares-ue",
    ),
    path(
        f"{_BASE_PROF}/<str:rf_professor>/",
        ObterNomePeloRFView.as_view(),
        name="professor-nome-rf",
    ),
]
